name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install wasm-pack
        run: npm install -g wasm-pack

      - name: Build World
        run: |
          cd crates/world
          wasm-pack build --target web --out-dir ../../packages/web/public/world

      - name: Install Node.js dependencies
        run: npm install

      - name: Build Next.js
        run: |
          cd packages/web
          npm run build

      # 8. GitHub Pages에 배포
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: web/out
      #     cname: www.harryplusplus.com # CNAME 파일 유지
